### ISSUE TITLE
Add schema migration support

### ISSUE THREAD

**Issue by hiteshjasani** [go-gorp/gorp#102]
It would be nice to have some mechanism to help migrate tables and columns over the life of a project.  Something to help support adding/removing columns, tables and indexes.

CreateTables*() and DropTables*() currently exist, but they are too broad brushed for my needs.  It would be nice to reduce the amount of sql I'm hand writing.

**Comment by GeertJohan** [comment]
Closing this. gorp has very basic create/drop table support which is very handy to quickly setup a database, but migrations go a lot further. Currently it is out of scope, there are a lot of tools better qualified for this. (goose, sql-migrate)
