### ISSUE TITLE
Question : Does gorp prevent SQL injection?

### ISSUE THREAD

**Issue by rvenugopal** [go-gorp/gorp#103]
Does Gorp prevent SQL injection?  Or would I need to use a separate library for sanitizing input for my application services.    

Thanks
-RV

**Comment by jackfranzen** [comment]
I'm sorry, just to make sure here. If we use "?" in the SQL and provide the strings as arguments in select, we're ok?

**Comment by purohit** [comment]
@jackfranzen : yes
