### ISSUE TITLE
To lower in PosgresDialect

### ISSUE THREAD

**Issue by PolluXxX** [go-gorp/gorp#119]
`func (d PostgresDialect) QuoteField(f string) string`

Why this function use strings.ToLower ?
`return " + strings.ToLower(f) + "`

I had to fix this in order to use datables with camelcase, like helloWorld.

With this function, datatable "helloWorld" become "helloworld" and it becomes impossible to use this datable with gorp ?

**Comment by GeertJohan** [comment]
Related to #192

**Comment by vinceyuan** [comment]
The table name of Postgres should not be forced to be lower case. 

All my existing table names look like "MyClasses". Though I have called `dbmap.AddTableWithName(MyClass{}, "MyClasses")`, the table name is still changed to "myclasses" by this line https://github.com/go-gorp/gorp/blob/develop/dialect.go#L295

Can I make a pull request to fix the table name?
