### ISSUE TITLE
Question for Multiple columns in key with Autoincrement

### ISSUE THREAD

**Issue by rvenugopal** [go-gorp/gorp#132]
I have a model

```
type User struct {
    Id int64 `db:"id"` // This is an autoincrement primary key
    ClientId int64 ``db:"client_id"`
    Name string...
}
```

I want to ensure that both Id and Client id form a key as in to update/read/delete a user record, the query should be 

```
"update... from User where id = :id and client_id = :client_id"
```
So multiple columns form the composite key but one of them (id) is autoincrement.  The call to SetKeys panics if AutoIncrement is set to true and multiple columns are specified.

Thanks
-Rv

**Comment by GeertJohan** [comment]
I agree with @tobz, closing this issue. @rvenugopal please re-open this issue if you feel there is a valid use case for this.
