### ISSUE TITLE
Autogenerate and UpdateOnInsert

### ISSUE THREAD

**Issue by NickNeedsAName** [go-gorp/gorp#140]
Hey,

I made a pull request for this issue, but basically if you've defined a field to have a default value on insertion, I coudlnt' figure out how to make gorp ignore the field on insert, but be aware of it on retrieval ("Transient" is either both there, or both not there).  Autogenerate is now in the ColumnMap and all it does is if a Column is set to Autogenerate then don't put it in the DB.

Along with this though I wanted to get the value that the DB creates for the autogenerated value on insertion, also not currently doable so I added in UpdateOnInsert to the ColumnMap as well.

**Comment by GeertJohan** [comment]
Related to #139

**Comment by GeertJohan** [comment]
I'll close this issue and continue with #139
