### ISSUE TITLE
Text field length

### ISSUE THREAD

**Issue by qrawl** [go-gorp/gorp#178]
Should we add a `maxsize:"n"` struct tag for GORP to check while creating tables?

**Comment by DavsX** [comment]
What about defining the column type (text in this case) via struct tag?

**Comment by qrawl** [comment]
@DavsX This is precisely what I suggest in #246:

    type Table struct {
        SomeField String `db:"size:30"`
    }

**Comment by DavsX** [comment]
@qrawl True, but I was thinking more of an explicit type:text tag

**Comment by qrawl** [comment]
That's... one step further qrawl@f7adc7a :)

I'm just waiting for #246 to be pulled :)

**Comment by DavsX** [comment]
Why nesting the tag? `db:"type:date"`? Go supports splitting them by space.
You could have:
```go
type MyStruct struct {
   name string `db:"db_name" primary_key:"true" type:"date"`
}
```

Then you could do:
```go
f.Tag.Get("db")
f.Tag.Get("primary_key")
f.Tag.Get("type")
```

I am new to golang, so please be patient :)

**Comment by qrawl** [comment]
By convention, we tend to let the tag keys be referenced from different packages. So for example you can save with gorp an unmarshaled JSON:

    type Person struct {
        Name    String `db:"name" json:"client_name"`
        Birthday time.Time `db:"type:date" json:"client_date_of_birth,omitempty"`
    }

**Comment by nelsam** [comment]
Another thing: the idiomatic thing for options seems to be that options *always* follow a comma.  For example:

```go
type Foo struct {
    Bar string `db:",pkey,size:50"`
}
```

Generally, it seems that the initial comma is required; should we be following that style?

Also, I'd like to consider an option registration framework ... actually, I'll just link to what I wrote for a different project: https://github.com/nelsam/requests/blob/master/tags.go

In that file, you can see how I allow users of the library to register their own options.  It allows for a *lot* more flexibility, especially for situations where someone needs an option that the library won't support natively (for example, if someone needs an option that isn't useful in any database engine other than the one they're using, it might not be something we want to add to gorp directly).  It also just helps reduce code bloat as we add more options to the library.

Granted, that may be something for another PR, later on.  Thoughts?

**Comment by qrawl** [comment]
@nelsam Honestly, I've only seen leading commas in tags when providing options while omitting a positional argument (as the field name for many parsers). My PR #246 lets you write tags in that way if you want to.

Regarding the tag parsing logic: I am not really into using third party libraries for these simple tasks. Is it worth it?

**Comment by nelsam** [comment]
@qrawl Sure, make sense.

As to the third party library: I don't want to use a third party library to parse it, I was just linking the code as an example of how we might allow users of gorp to register their own options.  Obviously, our option function would have a different signature (maybe `func(value string, col *ColumnMap) error` - allow the option function to modify the column map as it needs to based on the value), but something *similar* to the code I linked would be nice, for allowing users to register options that we don't support officially.

**Comment by GeertJohan** [comment]
I agree that the comma is only required to skip the first argument: the field name.

    Tag = Name { ','  Option }
    Option = OptionKey [ ':' OptionValue ]

**Comment by CureGecko** [comment]
I would also like a field length specifier so I don't have to include a create table SQL for people. But then again, it's likely that I will have to so when I have updates I can include upgrade sql files.

**Comment by qrawl** [comment]
PR #246
