### ISSUE TITLE
SelectOne with a null field will fail

### ISSUE THREAD

**Issue by shuhaowu** [go-gorp/gorp#181]
The following SQL will generate a problem:

	sql := "SELECT COUNT(items.Id) ItemCount, SUM(items.RemoteCount) RemoteCount FROM items"

Code: 

	type result struct {
		ItemsCount  int
		RemoteCount int
	}
	data := &result{}
	err := dbmap.SelectOne(data, sql)

Error:

    sql: Scan error on column index 1: converting string \"<nil>\" to a int: strconv.ParseInt: parsing \"<nil>\": invalid syntax

**Comment by GeertJohan** [comment]
I'm not sure if gorp should convert a null to a zero int.
How do you propose to solve this problem?

**Comment by GeertJohan** [comment]
The query returns null, which is not the same as zero. Use `*int` or a custom type to use with `sql.Scan`.
#221 might introduce these types into the package.
