### ISSUE TITLE
No table found for type

### ISSUE THREAD

**Issue by rajthilakmca** [go-gorp/gorp#184]
Hai, 

I am using beego webframework. I tried insert the datas to table, but get following error

Error: No table found for type: Users

Code : 
```go
type Users struct {
	Id            int64
	UserName      string
	ApiKey        string
	Authenticated bool
	Created       int64
}

func NewUser(username string, apikey string, auth bool) Users {
	return Users{
		UserName:      username,
		ApiKey:        apikey,
		Authenticated: auth,
		Created:       time.Now().UnixNano(),
	}
}

func Insert(dbmap *gorp.DbMap, user *utils.User) error {
	user_data := NewUser(user.Username, user.Api_key, true)
	err := dbmap.Insert(&user_data)
	return err
}
```

**Comment by PraGitHub** [comment]
I seem to have the same problem

**Comment by PraGitHub** [comment]
> 
> 
> I seem to have the same problem - **_No table found for type:_**
> Here is my code - [Code](https://github.com/PraGitHub/GoWebDevelopment/blob/master/WebApp/main.go#L363)
> 
> Part of code that leads to this error is below,
> `_, err = dbMap.Update(&user)`
> 
> Following is a line from my logs indicating the error message,
> 
> `2019/09/15 23:05:02.953207 P:/GoWebDevelopment/WebApp/main.go:365: /books/add id = 1866345757 error while updating user table, error = No table found for type:`
> 
> How do I fix it ?
> I did not find any other references :(

This - `_, err = dbMap.Update(user)` fixed the issue
