### ISSUE TITLE
Probably error in documentation 

### ISSUE THREAD

**Issue by dmitrykim** [go-gorp/gorp#2]
In tests you use mysql driver "github.com/ziutek/mymysql/godrv". With this driver 
db, err := sql.Open("mysql", "myuser:mypassword@localhost:3306/dbname")  // at https://github.com/coopernurse/gorp
doesn't work. 

Either documentation should be fixed to 
db, err := sql.Open("mymysql", "gomysql_test/gomysql_test/abc123")
or please point at mysql driver to use for current version of documentation

And sorry, don't know how to ask other way. In docs nothing is said about multithreading. I have many goroutines. Can I share 
two global variables 
var db *sql.DB
var dbmap *gorp.DbMap
among goroutines ? Or should I create single dbmap per goroutine (but single db *sql.DB)?  Couple of lines in documentation would be very useful

**Comment by geoah** [comment]
This indeed does seem to be an issue at least when using mymysql.
I'll try to create a test to reproduce this but it seems that we need to be using autorc to create and retrieve the db connection -- at least according to example number 6 of mymysql.
https://github.com/ziutek/mymysql#example-6---autoreconn-interface
