### ISSUE TITLE
When to use pointers and when not

### ISSUE THREAD

**Issue by matejkramny** [go-gorp/gorp#235]
The readme has multiple examples..

I get errors when doing `db.Insert(&dataModel)`

```
...
count, err = dbmap.Update(&p2)
...
```

Then in https://github.com/go-gorp/gorp/#update

```
// count is the # of rows updated, which should be 1 in this example
count, err := dbmap.Update(inv1)
```

What is correct? What is the difference?

This includes any methods taking an interface `Insert`, `Update`, `Delete`.

I understand why `Select` and `SelectOne` should take a pointer but not why the other methods should.

**Comment by sqdk** [comment]
You should always pass a pointer. What kind of error are you getting?

I think you are referring to an example where inv1 is already a pointer. Check the example just above it.

Not using pointers and passing by value would result in all objects being copied and passed to the function, which is pretty bad for memory usage. When you are handling a significant amount of data, you should always pass a pointer.

Passing pointers on inserts also allows gorp to set new auto increment id of the inserted object(s).

**Comment by matejkramny** [comment]
Sorry, i completely forgot that Go copies all the values and just realised that i was passing `**obj` which throws `2015/02/28 11:29:48 No table found for type:`

(it was pretty late, hmmm)

**Comment by sqdk** [comment]
Closing issue
