### ISSUE TITLE
SelectOne return an error even if query execution was successful

### ISSUE THREAD

**Issue by truongminh** [go-gorp/gorp#238]
Currently, if the result set is empty, SelectOne will return an error 
```Go
u := &User{}
dbmap.SelectOne(u, "SELECT * FROM user WHERE email = ?", email)
```
In a production environment, how to differentiate this error from ones made by other sources such as db connection?

**Comment by fzerorubigd** [comment]
If the result is not exactly one row, then this is correct behavior. See https://godoc.org/gopkg.in/gorp.v1#SelectOne

**Comment by truongminh** [comment]
@fzerorubigd Thank for your reply.
The error caused by SelectOne could be (1) no row, (2) multiple rows or (3) database error.
It is problematic to find out the exact causes.
I switch to the Select API, whose errors are clear.

**Comment by GeertJohan** [comment]
@truongminh So you're saying that the returned error should be clearer? We could change this issue to be about that..

**Comment by truongminh** [comment]
No, since SelectOne was designed to fail under these conditions.

**Comment by enahs** [comment]
while not necessarily an issue, It would be a nice to have if you could start classifying these errors in the style of database/sql. For instance, gorp.multipleRowsErr ala sql.NoRowsErr and then you could check for: 
```go
if err == gorp.multipleRowsErr {
 // something unexpected probably caused you to get in this state - do whatever your app does to resolve that.
}
```

**Comment by truongminh** [comment]
thank @enahs
