### ISSUE TITLE
How do I get the value of the "LastInsertId" after an Insert

### ISSUE THREAD

**Issue by UmeshVeerasingam** [go-gorp/gorp#242]
inv1 := &Invoice{"Welcome", "This is a welcome message"}

// Insert row
err := dbmap.Insert(inv1)

Lets say, I have a table name 'Invoice' and I have auto increment on the table's primary key (invoice_id). How do I get the primary key ID right after the insert?

**Comment by purohit** [comment]
https://godoc.org/github.com/coopernurse/gorp#DbMap.Insert

"Any interface whose TableMap has an auto-increment primary key will have
its last insert id bound to the PK field on the struct."

2015-03-19 19:48 GMT-06:00 UmeshVeerasingam <notifications@github.com>:

**Comment by UmeshVeerasingam** [comment]
I am sorry but  you didn't answer my question. I need it the last insert ID after I use Insert. Meaning, I want to know what was the value of the primary key after I inserted the latest row. The example below shows how to get the last insert id using db.Exec:
```
package main

import (
    "database/sql"
    _ "github.com/go-sql-driver/mysql"
)

func main() {
    db, err := sql.Open("mysql", "user:pass@/dbname")
    if err != nil {
        panic("Error opening DB:", err.Error())
    }
    defer db.Close()

    someParam := "value"

    if res, err := db.Exec(`INSERT INTO foo VALUES("bar", ?))`, someParam)
    if err != nil {
        println("Exec err:", err.Error())
    } else {
        id, err := res.LastInsertId()
        if err != nil {
            println("LastInsertId:", id)
        } else {
            println("Error:", err.Error())
        }
    }
} 
```
**Is there a way to get the last insert id using gorp?**

**Comment by sqdk** [comment]
Like purohit says, if you mapped the auto increment ID with tableMap.SetKeys, the id field will be automatically set to the last insert id.

There is an example in the README.

**Comment by UmeshVeerasingam** [comment]
@sqdk , @purohit 
Yes. I mapped the auto increment ID with tableMap.SetKeys. So if I do this:
```
inv1 := &Invoice{"Welcome", "This is a welcome message"}

err := dbmap.Insert(inv1)

last_insert_id := dbmap.LastInsertId()  //Will this return the last insert id for the insert above?
````
Can I get the last insert id by doing dbmap.LastInsertId()? - *see code above*

**Comment by sqdk** [comment]
No, inv1.id will contain the new ID. 

Just as it right here: https://github.com/go-gorp/gorp#insert in the README.

**Comment by UmeshVeerasingam** [comment]
Thank you @sqdk 
That worked!
