### ISSUE TITLE
Timeout support?

### ISSUE THREAD

**Issue by kristen1980** [go-gorp/gorp#261]
What is the best way to make a query timeout? I thought about using a channel to execute the query but wondered if there's a better way. I am using Postgresql, which also has "STATEMENT_TIMEOUT" but I get the following when I run it:

    stmt := "BEGIN; SET SESSION STATEMENT_TIMEOUT TO 5000; COMMIT; Select id, name FROM     
    mytable WHERE name = $1 AND occupation = $2"
    if _, err := dbmap.Select(&rows, stmt, params...); err != nil {
		    log.Println(err)
    }

Err:
    pq: cannot insert multiple commands into a prepared statement

(The statement runs fine if I omit setting the timeout)
Thanks!

**Comment by kristen1980** [comment]
I didn't see a PreGet method listed for a hook but I tried:

func (p *Person) PreGet(s gorp.SqlExecutor) error {
	log.Println("Resetting timeout...")
	if _, err := dbmap.Exec("BEGIN; SET SESSION STATEMENT_TIMEOUT TO 1; COMMIT;"); err != nil {
		log.Println(err)
	}
	return nil
}

but it doesn't seem to execute ;(

**Comment by nelsam** [comment]
FYI, `BEGIN` opens a transaction, then `COMMIT` closes the transaction (which, I believe, closes the current "session", reverting that timeout) - you probably don't want that.  Furthermore, even if you set your session's `statement_timeout` outside of a transaction, Go's `database/sql` library uses a connection pool under the covers - meaning that the next SQL statement will most likely execute in a different connection (and, therefore, a different session which probably doesn't have the statement_timeout set).  What you probably want to do:

```go
// Errors ignored for brevity; don't ignore the errors in production code
tx, _ := dbmap.Begin() // A transaction is guaranteed to be run in the same session
_, _ = tx.Exec("SET STATEMENT_TIMEOUT TO 1")
res, _ := tx.Get(new(Person{}), someID)
p := res.(*Person)
```

If you wanted to set the timeout on the PreGet method (and ensure that a person is never loaded outside of a transaction):

```go
func (p *Person) PreGet(exec gorp.SqlExecutor) error {
    tx, ok := exec.(*gorp.Transaction)
    if !ok {
        return errors.New("Cannot get a Person outside of a transaction")
    }
    if _, err := tx.Exec("SET SESSION STATEMENT_TIMEOUT TO 1")
    if err != nil {
        return err
    }
    return nil
}
```
