### ISSUE TITLE
Make it possible to get "CREATE TABLE ..." sql as string

### ISSUE THREAD

**Issue by alexflint** [go-gorp/gorp#263]
I would like to be able to get the `CREATE SCHEMA` and `CREATE TABLE` sql constructed within DbMap.createTables as a string. How about moving the logic for constructing the sql strings from `DbMap.createTables` to `TableMap.SqlForCreate` (and then have `DbMap.createTables` simple call `t.SqlForCreate` for each table)?

**Comment by GeertJohan** [comment]
Merged #264
