### ISSUE TITLE
Model struct fields are not found during fetch when size: tag is present

### ISSUE THREAD

**Issue by cs2dsb** [go-gorp/gorp#266]
Split from #265 as requested by @GeertJohan 

Fields with size: specified are not found when mapping sql column results back to the structure.

I'm using Windows. I've taken code @qrawl posted in #265 and added a fetch after creating the database and I get the same error I was having "no fields [...] in Post" - the missing fields correspond to those with size: set.

The full code, the log and a screenshot of the database it created are [in this gist](https://gist.github.com/cs2dsb/5a0efee98e1725fd2723)

I've was using postgres when I originally had the issue but this example is using sqllite for ease of sharing.

**Comment by qrawl** [comment]
Match function at gorp.go:1852 doesn't take into account multiple tags. I'm on it

**Comment by GeertJohan** [comment]
Thanks @cs2dsb for creating a detailed report
