### ISSUE TITLE
test_all.sh is buggy and inflexible

### ISSUE THREAD

**Issue by rickb777** [go-gorp/gorp#274]
The test_all script works only for those who read it and install the necessary tools in the right place. We can do better.  Please see the patch attached.

**Comment by rickb777** [comment]
Nope. Can't attach a patch file. How USELESS is Github.

**Comment by rickb777** [comment]
diff --git a/test_all.sh b/test_all.sh
index 20cf15a..0a6dc99 100755
--- a/test_all.sh
+++ b/test_all.sh
@@ -1,12 +1,10 @@
-#!/bin/bash
+#!/bin/bash -e
 
 # on macs, you may need to:
 # export GOBUILDFLAG=-ldflags -linkmode=external
 
 coveralls_testflags="-v -covermode=count -coverprofile=coverage.out"
 
-set -e
-
 echo "Testing against mysql"
 export GORP_TEST_DSN=gorptest/gorptest/gorptest
 export GORP_TEST_DIALECT=mysql
@@ -26,8 +24,15 @@ echo "Testing against sqlite"
 export GORP_TEST_DSN=/tmp/gorptest.bin
 export GORP_TEST_DIALECT=sqlite
 go test $coveralls_testflags $GOBUILDFLAG $@ .
-
-if [[ `go version` == *"1.4"* ]]
-then
-	$HOME/gopath/bin/goveralls -covermode=count -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
-fi
+rm -f /tmp/gorptest.bin
+
+case $(go version) in
+  *go1.4*)
+    if [ "$(type -p goveralls)" != "" ]; then
+	  goveralls -covermode=count -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
+    elif [ -x $HOME/gopath/bin/goveralls ]; then
+	  $HOME/gopath/bin/goveralls -covermode=count -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
+    fi
+  ;;
+  *) ;;
+esac

**Comment by GeertJohan** [comment]
I totally agree! I dont care much for a stable master branch at this point because of the phase1.. But this should definitly happen in phase3, its essential for a stable v2 release. Maybe Ill just apply this now, still in phase1 (I dont see why not, but its late and I need sleep first).

There will be a lot more changes in phase3 regarding testing etc.
