### ISSUE TITLE
DB Tag not working with Postgresql

### ISSUE THREAD

**Issue by justintv90** [go-gorp/gorp#283]
I just put the db tag like the example

    type Post struct {
    	ID       int64  `db:"uID"`
    	Username string `db:"uUsername"`
    	Title    string `db:",size:50"`               // Column size set to 50
    	Body     string `db:"article_body,size:1024"` // Set both column name and size
    }

But when i create table, the database create the table name with whole tag options like the screenshoot below. 

http://i.imgur.com/v11EgR0.png

Please help me

**Comment by qrawl** [comment]
How do you import GORP in your code? Are you using `import "gopkg.in/gorp.v1"`?

**Comment by justintv90** [comment]
Ok qrawl, i got it. Thanks so much for your help
