### ISSUE TITLE
db tag not working. Column name becomes ",size:50" for field Title string `db:",size:50"` 

### ISSUE THREAD

**Issue by vinceyuan** [go-gorp/gorp#287]
I am new to gorp and following the [QuickStart](https://github.com/go-gorp/gorp#quickstart). I found db tag is not working. The column for field `Title` becomes `,size:50` instead of `Title`. The column for field `Body` becomes `article_body,size:1024` instead of `article_body`. My dev env: OS X Yosemite, golang 1.5.

```
type Post struct {
    // db tag lets you specify the column name if it differs from the struct field
    Id      int64  `db:"post_id"`
    Created int64
    Title   string `db:",size:50"`               // Column size set to 50
    Body    string `db:"article_body,size:1024"` // Set both column name and size
}
```

```
sqlite> .schema posts
CREATE TABLE "posts" ("post_id" integer not null primary key autoincrement, "Created" integer, ",size:50" varchar(255), "article_body,size:1024" varchar(255));
```

**Comment by qrawl** [comment]
The `size` feature is only available on the development branch. If you feel adventurous, try with

    import "github.com/go-gorp/gorp"

**Comment by vinceyuan** [comment]
@qrawl I suggest we modify the [Quickstart](https://github.com/go-gorp/gorp#quickstart), because new users like me do not know this rule. They just follow the steps in README but find the code does not work as expected. Thanks.

**Comment by qrawl** [comment]
You are right. This was meant to be a transitory condition. This should be addressed soon.
