### ISSUE TITLE
Postgresql can't use timestamp

### ISSUE THREAD

**Issue by jadeydi** [go-gorp/gorp#330]
likes, _ := apiDbMap.SelectInt("SELECT count(*) FROM cast_likers, (SELECT casts.id FROM casts LEFT JOIN devices ON devices.id=casts.device_id WHERE devices.platform=$1) casts WHERE casts.id=cast_likers.cast_id AND cast_likers.created_at>=$2 AND cast_likers.created_at<= timestamp $2 + interval '1 hour'", platform, measuredAt.Format(time.RFC1123Z))

If i add timestamp, sql can't exec. error of Postgresql.

ERROR:  syntax error at or near "$2" at character 248

**Comment by nelsam** [comment]
In postgres, `timestamp '<timestamp'` only works with literals and can't be used in prepared statements.  Try changing `timestamp $2` to `$2::timestamp`.
