### ISSUE TITLE
support Go Modules?

### ISSUE THREAD

**Issue by Songmu** [go-gorp/gorp#403]
Since v1 and v2 tags are mixed without placing go.mod, I think it's better to bump v3 and support Go Modules.

I could make a pull request for it. How about it?

**Comment by nelsam** [comment]
I'd be happy to create a v3.0.0 with modules support!  I'm not putting them in master (at least, not yet), as I hate frozen dependencies on branches not marked "stable" - but I will happily create future v3 releases using the first v3.0.0 `go.mod` and `go.sum` files.

**Comment by nelsam** [comment]
I pushed up a branch w/ `go.mod` and `go.sum` named `v3` to keep track of changes over time, and tagged the initial commit as `v3.0.0`.  Please reopen if you have any problems with it!

FWIW, 100% of `gorp`'s non-test dependencies are in the standard library.

Test deps (which are in `go.mod`) include the sql drivers we test against, [`onpar`](https://github.com/poy/onpar) for our unit tests, [`testify`](https://github.com/stretchr/testify) for our integration tests, and a few indirect dependencies.

I'll make a release w/ release notes for that tag later, but I'm running late at the moment and need to take off.
