### ISSUE TITLE
v3 module naming causes error when requested

### ISSUE THREAD

**Issue by andreiavrammsd** [go-gorp/gorp#410]
Hello,

The [v3.0.0](https://github.com/go-gorp/gorp/releases/tag/v3.0.0) release introduced this package as a module. And I'm having troubles requesting that specific version.

`go get github.com/go-gorp/gorp/v3`

gives

`go get github.com/go-gorp/gorp/v3: module github.com/go-gorp/gorp@upgrade found (v2.2.0+incompatible), but does not contain package github.com/go-gorp/gorp/v3`

Maybe because the module path is not as per [indications here](https://github.com/golang/go/wiki/Modules#semantic-import-versioning). Module path should be `github.com/go-gorp/gorp/v3`.

Thank you,
Andrei

**Comment by nelsam** [comment]
Whoops!  Thanks for letting us know!

**Comment by nelsam** [comment]
I've released `v3.0.1` with a fixed `module` statement in `go.mod`.  Please reopen if that doesn't resolve the issue for you (i.e. if I need to scrap `v3.0.0` because of the borked `go.mod` file).

**Comment by andreiavrammsd** [comment]
Looks good, thank you!
