### ISSUE TITLE
Get without assertion

### ISSUE THREAD

**Issue by tcurdt** [go-gorp/gorp#414]
Is there a particular reason for this

```
obj, err := dbmap.Get(Person{}, p1.Id)
p2 := obj.(*Person)
```

instead of

```
p2 := Persion{}
err := dbmap.Get(&p2, p1.Id)
```
The latter feels more in line with the rest of the methods and avoids the assertion.

**Comment by nelsam** [comment]
Mostly legacy and backwards compatibility.  If you'd like to add logic in `Get` to just populate fields of pointer values directly, feel free to make a PR.  However, don't change the existing logic.

**Comment by tcurdt** [comment]
Making that change but keeping the signature backwards compatible is probably not really that useful.
I guess I'll just use my own wrapper then. But thanks for the quick feedback!
