### ISSUE TITLE
Close prepared statement in (*Transaction).Exec to avoid leaking PostgreSQL prepared statements

### ISSUE THREAD

**Issue by sqs** [go-gorp/gorp#48]
When I run a lot of queries in a single connection, PostgreSQL's memory usage steadily increases (up to 13 GB after ~100k queries, at which point my computer locks up). I think this is because it does not garbage-collect prepared statements that are created in a connection until the connection is closed. The following patch fixes the issue; PostgreSQL memory usage is drastically lower after running 100k queries.

Has anybody else had the same issue?

``` diff
diff --git a/gorp.go b/gorp.go
index 4086b6b..b7bbfc6 100644
--- a/gorp.go
+++ b/gorp.go
@@ -931,6 +931,7 @@ func (t *Transaction) Exec(query string, args ...interface{}) (sql.Result, error
        if err != nil {
                return nil, err
        }
+       defer stmt.Close()
        return stmt.Exec(args...)
 }
```

**Comment by ErgjanJaha** [comment]
This just saved me a ton of time, was missing that myself in my  code and couldn't tell what was leaking
